version: '3.1'

services:

  questions_postgres_db:
    image: postgres
    volumes:
      - questions-db-data:/var/lib/postgresql/data/
    restart: always
    ports:
    - 5432:5432
    env_file:
      - questions_db_postgres.env
  context_redis_db:
    image: redis
    ports:
      - "6379:6379"


volumes:
  questions-db-data: