version: '3.1'

services:

  questions_postgres_db:
    build: .
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: artem_priglasil
      POSTGRES_PASSWORD: 4r73m_pr1gl451l
      POSTGRES_DB: questions
  context_redis_db:
    image: redis
    ports:
      - "6379:6379"


volumes:
  questions-db-data:
