version: '3.1'

services:

  postgres_db:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: always
    ports:
    - 5432:5432
    env_file:
      - postgres.env


volumes:
  database-data: